# Generated by Django 5.1.2 on 2024-11-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='peridodo',
            new_name='periodo',
        ),
    ]
